### ISSUE TITLE
Lie about my country

### ISSUE THREAD

**Issue by samikeijonen** [radishconcepts/edd-vatinfoeu-dev#3]
If I lie my country at the checkout, I can still purchase without any errors. For example I can change my county from Finland to Fiji and I get the product with zero tax. Should it be this way?

**Comment by samikeijonen** [comment]
In other words does API check IP address match to selected country?

**Comment by coenjacobs** [comment]
Yes, this plugin does not do the evidence collection for EU VAT compliance, it just provides the right tax rates for now. We might look into adding this or improving compatibility with existing plugins that already do this. Do you know any plugins that do this for Easy Digital Downloads? Thanks for testing!

**Comment by samikeijonen** [comment]
I'm testing and using Taxamo integration for now. It has couple of other issues but it checks your country from IP and can also check VAT number. Those would be great features in this plugin also.

https://github.com/rhyswynne/easy-digital-downloads-taxamo-integration

http://www.taxamo.com/

**Comment by coenjacobs** [comment]
Thanks for the feedback @samikeijonen. We have actually added this to the API early this week and have implemented it in the WooCommerce plugin already. I'm implementing it in this EDD plugin today.

**Comment by samikeijonen** [comment]
Looking really good. Let me know when I can do another test round.

**Comment by coenjacobs** [comment]
This can now be tested on [the 1.0.0 branch](https://github.com/radishconcepts/edd-vatinfoeu-dev/tree/1.0.0), doing final checks and tweaks in #6.
